base_url = "https://bobrockefeller.com"

title = "Bob Rockefeller"
description = "What is Bob up to now?"

compile_sass = false

build_search_index = false

output_dir = "_site"

taxonomies = [
  {name = "tags", paginate_by = 4},
  {name = "categories", paginate_by = 4},
]

[markdown]
  external_links_target_blank = true
  external_links_no_follow = true
  smart_punctuation = true
  definition_list = true

[markdown.highlighting]
  theme = "one-dark-pro"

[extra]

menus = [
  { name = "Home", url = "/", trailing_slash = true },
  { name = "About", url = "/about/", trailing_slash = true },
  { name = "Categories", url = "/categories/", trailing_slash = true },
  { name = "Tags", url = "/tags/", trailing_slash = true }
]
